from tkinter import *
root = Tk()
root.geometry("200x287")
root.title("Calculator")

def click(event):
    global scvalue
    text = event.widget.cget("text")
    # print(text)
    if text == "=":
        if scvalue.get().isdigit():
            value = int(scvalue.get())
        else:
            try:
                value = eval(screen.get())
            except Exception as e:
                scvalue.set("Error")
                screen.update()
        scvalue.set(value)
        screen.update()
    elif text == "c":
        scvalue.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get()+text)
        screen.update()
scvalue = StringVar()
scvalue.set("")
screen = Entry(root,textvariable=scvalue,font="lucidaa 20 bold")
screen.pack(fill=X,pady=5,padx=2)

f2 = Frame(root,bg="grey")
f2.pack(side=TOP,fill=BOTH)
b = Button(f2,text="9",font="lucida 22 bold",width=2,height=1)
b.pack(padx=2,side=RIGHT,fill=BOTH)
b.bind('<Button-1>',click)
b = Button(f2,text="8",font="lucida 22 bold",width=2,height=1)
b.pack(padx=2,side=RIGHT)
b.bind('<Button-1>',click)
b = Button(f2,text="7",font="lucida 22 bold",width=2,height=1)
b.pack(padx=2,side=RIGHT)
b.bind('<Button-1>',click)
b = Button(f2,text="c",font="lucida 22 bold",width=2,height=1)
b.pack(padx=2,side=RIGHT)
b.bind('<Button-1>',click)

f2 = Frame(root,bg="grey")
f2.pack(side=TOP,fill=BOTH)
b = Button(f2,text="6",font="lucida 22 bold",width=2,height=1)
b.pack(padx=2,side=RIGHT)
b.bind('<Button-1>',click)
b = Button(f2,text="5",font="lucida 22 bold",width=2,height=1)
b.pack(padx=2,side=RIGHT)
b.bind('<Button-1>',click)
b = Button(f2,text="4",font="lucida 22 bold",width=2,height=1)
b.pack(padx=2,side=RIGHT)
b.bind('<Button-1>',click)
b = Button(f2,text="/",font="lucida 22 bold",width=2,height=1)
b.pack(padx=2,side=RIGHT)
b.bind('<Button-1>',click)

f2 = Frame(root,bg="grey")
f2.pack(side=TOP,fill=BOTH)
b = Button(f2,text="3",font="lucida 22 bold",width=2,height=1)
b.pack(padx=2,side=RIGHT)
b.bind('<Button-1>',click)
b = Button(f2,text="2",font="lucida 22 bold",width=2,height=1)
b.pack(padx=2,side=RIGHT)
b.bind('<Button-1>',click)
b = Button(f2,text="1",font="lucida 22 bold",width=2,height=1)
b.pack(padx=2,side=RIGHT)
b.bind('<Button-1>',click)
b = Button(f2,text="*",font="lucida 22 bold",width=2,height=1)
b.pack(padx=2,side=RIGHT)
b.bind('<Button-1>',click)

f2 = Frame(root,bg="grey")
f2.pack(side=TOP,fill=BOTH)
b = Button(f2,text="=",font="lucida 22 bold",width=2,height=1)
b.pack(padx=2,side=RIGHT)
b.bind('<Button-1>',click)
b = Button(f2,text="0",font="lucida 22 bold",width=2,height=1)
b.pack(padx=2,side=RIGHT)
b.bind('<Button-1>',click)
b = Button(f2,text="+",font="lucida 22 bold",width=2,height=1)
b.pack(padx=2,side=RIGHT)
b.bind('<Button-1>',click)
b = Button(f2,text="-",font="lucida 22 bold",width=2,height=1)
b.pack(padx=2,side=RIGHT)
b.bind('<Button-1>',click)


root.mainloop()